#!/bin/sh

docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="America/Los_Angeles" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "$(pwd)/zm":"/config":rw \
-v "$(pwd)/zm/data":"/var/cache/zoneminder":rw \
--device /dev/video0:/dev/pv_stats_cam \
--device /dev/video1:/dev/video1 \
--device /dev/video2:/dev/outdoor_cam \
dlandon/zoneminder